# Generated by Django 5.1.4 on 2026-06-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_backgrounds/'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='theme',
            field=models.CharField(choices=[('default', 'Стандартна'), ('dark', 'Темна'), ('blue', 'Синя'), ('green', 'Зелена'), ('pink', 'Рожева'), ('purple', 'Фіолетова')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Приватний'), ('group', 'Груповий')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_theme', models.CharField(blank=True, choices=[('default', 'Стандартна'), ('dark', 'Темна'), ('blue', 'Синя'), ('green', 'Зелена'), ('pink', 'Рожева'), ('purple', 'Фіолетова')], max_length=20, null=True)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='chat_backgrounds/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
